# Generated by Django 4.2.5 on 2023-10-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vn_name', models.CharField(max_length=255)),
                ('vn_slug', models.SlugField(max_length=250)),
                ('en_name', models.CharField(max_length=255)),
                ('en_slug', models.SlugField(max_length=250)),
                ('vn_description', models.TextField(blank=True, null=True)),
                ('en_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
