# Generated by Django 4.2.5 on 2023-10-09 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_imagegallery_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vn_name', models.CharField(max_length=255)),
                ('vn_slug', models.SlugField(max_length=250)),
                ('en_name', models.CharField(max_length=255)),
                ('en_slug', models.SlugField(max_length=250)),
                ('vn_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagegallery', to='gallery.gallerycategories'),
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediagallery', to='gallery.gallerycategories'),
        ),
    ]
