# Generated by Django 4.2.5 on 2023-10-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallerycategories_imagegallery_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='imagine/'),
        ),
    ]
