# Generated by Django 4.2.5 on 2023-10-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_imagelanding_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelanding',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=250, unique=True),
        ),
    ]
