# Generated by Django 4.2.5 on 2023-10-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_imagelanding_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelanding',
            name='image',
            field=models.ImageField(upload_to='imagine/'),
        ),
        migrations.AlterField(
            model_name='imagelanding',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
