# Generated by Django 4.2.5 on 2023-10-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_imagelanding_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vn_name', models.CharField(max_length=255)),
                ('en_name', models.CharField(max_length=255)),
            ],
        ),
    ]
