# Generated by Django 4.2.5 on 2023-10-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_aboutuscategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUsCategory',
        ),
    ]
