# Generated by Django 4.2.5 on 2023-10-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_delete_aboutuscategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vn_name', models.CharField(max_length=255)),
                ('vn_slug', models.SlugField(max_length=250)),
                ('en_name', models.CharField(max_length=255)),
                ('en_slug', models.SlugField(max_length=250)),
            ],
        ),
    ]
