# Generated by Django 4.2.5 on 2023-10-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_imagelanding_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='image',
            field=models.ImageField(blank=True, upload_to='imagine/'),
        ),
    ]
