# Generated by Django 4.2.5 on 2023-10-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubMenu',
        ),
    ]
