# Generated by Django 4.2.5 on 2023-10-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_address_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='en_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='vn_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
