# Generated by Django 4.2.5 on 2023-10-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_address_en_description_address_vn_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='description',
        ),
    ]
