# Generated by Django 4.2.5 on 2023-10-20 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_address_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=250)),
                ('google_map_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('vn_address', models.TextField(blank=True, null=True)),
                ('en_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
