# Generated by Django 4.2.5 on 2023-10-20 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_contactinformation_delete_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinformation',
            old_name='en_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='vn_address',
        ),
    ]
