# Generated by Django 4.2.5 on 2023-10-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actions',
            new_name='Action',
        ),
        migrations.RenameModel(
            old_name='ActionsCategories',
            new_name='ActionsCategory',
        ),
    ]
