# Generated by Django 4.2.5 on 2023-10-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_rename_actions_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionscategory',
            name='en_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
