# Generated by Django 4.2.5 on 2023-10-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_actionscategory_en_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='image',
            field=models.ImageField(null=True, upload_to='imagine/'),
        ),
    ]
