# Generated by Django 4.2.5 on 2023-10-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_alter_action_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='image',
            field=models.ImageField(blank=True, upload_to='imagine/'),
        ),
        migrations.AlterField(
            model_name='action',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
    ]
